version: '3.8'

services:
  app:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
